[package]
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
name = "pdfreader-search"
description = "Text extraction pipeline, index and query"
publish = false

[dependencies]
pdfreader-core = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
