//! Phase 3 corpus tests: open fixtures without panic, and verify that an
//! encrypted document is detected and surfaces `PasswordRequired`.
//!
//! Fixtures live under `target/test-pdfs` (generated by
//! `tools/generate_fixtures.py`). They are produced by a separate Python step,
//! so each test skips cleanly when the fixtures are absent rather than failing
//! the whole suite in environments that have not generated them.

use std::path::PathBuf;

use pdfreader_pdf::EngineError;
use pdfreader_pdf::engine::{PdfEngine, PdfiumEngine};

/// Workspace root, derived from this crate's manifest directory.
fn workspace_root() -> PathBuf {
    // crates/pdf -> ../.. -> repo root
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
}

/// Locate the staged PDFium library, scanning `target/native/*`.
fn find_pdfium() -> Option<PathBuf> {
    let native = workspace_root().join("target").join("native");
    let entries = std::fs::read_dir(&native).ok()?;
    for entry in entries.flatten() {
        let dir = entry.path();
        if dir.join("pdfium.dll").exists()
            || dir.join("libpdfium.so").exists()
            || dir.join("libpdfium.dylib").exists()
        {
            return Some(dir);
        }
    }
    None
}

fn fixture(name: &str) -> PathBuf {
    workspace_root().join("target").join("test-pdfs").join(name)
}

/// Skip a test with a clear message when its fixture is missing.
fn require_fixture(name: &str) -> PathBuf {
    let path = fixture(name);
    if !path.exists() {
        eprintln!(
            "SKIP: fixture {} not found (run: python3 tools/generate_fixtures.py target/test-pdfs)",
            path.display()
        );
        std::process::exit(0);
    }
    path
}

#[test]
fn unencrypted_fixtures_open_cleanly() {
    let Some(dir) = find_pdfium() else {
        eprintln!("SKIP: no PDFium library staged under target/native");
        return;
    };

    let mut engine = PdfiumEngine::bind(Some(&dir)).expect("pdfium should bind");

    for (name, pages) in [("small-3p.pdf", 3u32), ("large-500p.pdf", 500u32)] {
        let path = require_fixture(name);
        let (_handle, info) = engine
            .open(&path, None)
            .unwrap_or_else(|e| panic!("{name}: open failed: {e}"));

        assert_eq!(info.pages.len() as u32, pages, "{name}: page count");
        assert!(!info.encrypted, "{name}: must not be flagged encrypted");
    }
}

#[test]
fn encrypted_fixture_requires_a_password() {
    let Some(dir) = find_pdfium() else {
        eprintln!("SKIP: no PDFium library staged under target/native");
        return;
    };

    let mut engine = PdfiumEngine::bind(Some(&dir)).expect("pdfium should bind");
    let path = require_fixture("encrypted.pdf");

    // Opening with no password must be rejected with PasswordRequired, which is
    // the signal the UI turns into a prompt.
    let err = engine
        .open(&path, None)
        .expect_err("encrypted doc must reject an empty password");

    assert!(
        matches!(err, EngineError::PasswordRequired),
        "expected PasswordRequired, got {err:?}"
    );
}

/// Opens the encrypted fixture with its known password.
///
/// Ignored by default: it depends on a byte-exact standard-security-handler
/// implementation, which is deferred to the Phase 8 crypto libraries
/// (`lopdf`/`krilla`). The `PasswordRequired` trigger above is the behaviour
/// Phase 3 actually needs (the UI prompts); this is the deeper round-trip.
#[test]
#[ignore = "requires byte-exact PDF security-handler crypto (Phase 8)"]
fn encrypted_fixture_opens_with_password() {
    let Some(dir) = find_pdfium() else {
        eprintln!("SKIP: no PDFium library staged under target/native");
        return;
    };

    let mut engine = PdfiumEngine::bind(Some(&dir)).expect("pdfium should bind");
    let path = require_fixture("encrypted.pdf");

    let (_handle, info) = engine
        .open(&path, Some("secret"))
        .expect("open with the correct password must succeed");

    assert!(info.encrypted);
    assert_eq!(info.pages.len(), 3);
}
